# CONFIG FILES
# Here you can define protected blocks

protectedBlocks:
  - ARMOR_STAND
  # You can add the list of protected blocks here

blockPlaceError: "&cYou cannot place this block!"
blockBreakError: "&cYou cannot break this block!"

messages:
  noBlockedBlocks: "&aNo blocks are blocked."
  blockedBlocksHeader: "&eBlocked blocks:"